# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f12f4fbb73f31e6e4ed0897e7a94b799e00417986c144e894690045b8adb5e8a95f4f3a0416102c9fc90d50b9c4d36a5cc3cbcb8d04f02fed7aa6db4399368ac

test:
  secret_key_base: 1a9c490ffa9a95caa8e790102f8293891352212ebea4e93f65bf148aaec4afb3c9a68f46a5729e3919209be5d26f12ec5b962fa14d0b87da0e2d7264e95b09eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
